

comp = {'categories': [{'name': 'UTR Men', 'slug': 'utr-men', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'id': 1843, 'flag': 'utr-men'}, {'name': 'UTR Women', 'slug': 'utr-women', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'id': 1844, 'flag': 'utr-women'}, {'name': 'Grand Slam', 'slug': 'grand-slam', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 1000, 'id': -100, 'flag': 'grand-slam'}, {'name': 'United Cup', 'slug': 'united-cup', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 0, 'id': 1705, 'flag': 'united-cup'}, {'name': 'ATP', 'slug': 'atp', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 7, 'id': 3, 'flag': 'atp', 'fieldTranslations': {'nameTranslation': {'ar': 'رابطة محترفي التنس', 'hi': 'डब्ल्यूटीए', 'bn': 'এটিপি'}, 'shortNameTranslation': {}}}, {'name': 'ITF Women', 'slug': 'itf-women', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 2, 'id': 213, 'flag': 'itf-women'}, {'name': 'ITF Men', 'slug': 'itf-men', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 3, 'id': 785, 'flag': 'itf-men'}, {'name': 'Davis Cup', 'slug': 'davis-cup', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 0, 'id': 76, 'flag': 'davis-cup'}, {'name': 'WTA 125', 'slug': 'wta-125', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 4, 'id': 871, 'flag': 'wta-125'}, {'name': 'In Progress', 'slug': 'in-progress', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 1001, 'id': -101, 'flag': 'in-progress'}, {'name': 'Challenger', 'slug': 'challenger', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 5, 'id': 72, 'flag': 'challenger', 'fieldTranslations': {'nameTranslation': {'ar': 'تحدي (تنس)', 'hi': 'डेनमार्क', 'bn': 'চ্যালেঞ্জার'}, 'shortNameTranslation': {}}}, {'name': 'Exhibition', 'slug': 'exhibition', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 0, 'id': 79, 'flag': 'exhibition'}, {'name': 'WTA', 'slug': 'wta', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 6, 'id': 6, 'flag': 'wta', 'fieldTranslations': {'nameTranslation': {'ar': 'رابطة لاعبات التنس', 'hi': 'चैलेंजर', 'bn': 'ডব্লিউটিএ'}, 'shortNameTranslation': {}}}, {'name': 'Billie Jean King Cup', 'slug': 'billie-jean-king-cup', 'sport': {'name': 'Tennis', 'slug': 'tennis', 'id': 5}, 'priority': 0, 'id': 74, 'flag': 'billie-jean-king-cup'}]}


for key, value in comp.items():
    if isinstance(value, list):
        for item in value:
            print(item.get("name"), ",",  item.get("id"))
    else:
        print(key, value)
